version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/src
      - ./backend/public/upload:/usr/src/app/public/upload
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    networks:
      - backend-network

  cms:
    build:
      context: ./cms
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
    depends_on:
      - backend
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    depends_on:
      - backend
    networks:
      - backend-network

  # db:
  #   image: mariadb:10.6
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_USER=testuser
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_TCP_PORT=3307
  #     - MYSQL_DATABASE=desanuaniali
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - backend-network

#   phpmyadmin:
#     image: phpmyadmin
#     restart: always
#     ports:
#       - '8000:80'
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_PORT=3307
#       - PMA_HOST=db
#       - PMA_PASSWORD=password
#       - PMA_USER=testuser
#     networks:
#       - backend-network
# volumes:
#   db_data:
networks:
  backend-network:
    driver: bridge
